{{- $postgresqlValues := dict
  "name" .Values.postgresql.primary.initdb.scriptsConfigMap
  "username" .Values.postgresql.auth.username
  "database" .Values.postgresql.auth.database
  "root" $ -}}
{{- include "peaka.postgresql.initScripts" $postgresqlValues }}

---

{{ $postgresqlBigtableValues := dict
  "name" .Values.postgresqlbigtable.primary.initdb.scriptsConfigMap
  "username" .Values.postgresqlbigtable.auth.username
  "database" .Values.postgresqlbigtable.auth.database
  "root" $ -}}
{{- include "peaka.postgresql.initScripts" $postgresqlBigtableValues -}}
