{{- if gt (int .Values.trino.server.workers) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "peaka.trino.worker" . }}
  labels:
    app: {{ template "peaka.trino.fullname" . }}
    chart: {{ template "peaka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
data:
  node.properties: |
    node.environment={{ .Values.trino.server.node.environment }}
    node.data-dir={{ .Values.trino.server.node.dataDir }}
    plugin.dir={{ .Values.trino.server.node.pluginDir }}
  {{- range $configValue := .Values.trino.additionalNodeProperties }}
    {{ $configValue }}
  {{- end }}

  jvm.config: |
    -server
    -Xmx{{ .Values.trino.worker.jvm.maxHeapSize }}
    -XX:+{{ .Values.trino.worker.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.trino.worker.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    -XX:ReservedCodeCacheSize=512M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.nio.maxCachedBufferSize=2000000
    -Dfile.encoding=UTF-8
    -XX:+UnlockDiagnosticVMOptions
    -XX:GCLockerRetryAllocationCount=32
  {{- if .Values.trino.server.kerberosConfig }}
    -Djava.security.krb5.conf={{ .Values.trino.server.kerberosConfigPath }}/krb5.conf
  {{- end }}
  {{- range $configValue := .Values.trino.worker.additionalJVMConfig }}
    {{ $configValue }}
  {{- end }}

  config.properties: |
    coordinator=false
    http-server.http.port={{ .Values.trino.service.port }}
    http-server.process-forwarded=true
    query.max-memory={{ .Values.trino.server.config.query.maxMemory }}
    query.max-memory-per-node={{ .Values.trino.worker.config.query.maxMemoryPerNode }}
    query.max-length={{ .Values.trino.worker.config.query.maxLength }}
  {{- if .Values.trino.worker.config.memory.heapHeadroomPerNode }}
    memory.heap-headroom-per-node={{ .Values.trino.worker.config.memory.heapHeadroomPerNode }}
  {{- end }}
    discovery.uri=http://{{ template "peaka.trino.fullname" . }}:{{ .Values.trino.service.port }}
  {{- range $configValue := .Values.trino.additionalConfigProperties }}
    {{ $configValue }}
  {{- end }}
  {{ .Values.trino.server.workerExtraConfig | indent 4 }}

  exchange-manager.properties: |
    exchange-manager.name={{ .Values.trino.server.exchangeManager.name }}
  {{ if eq .Values.trino.server.exchangeManager.name  "filesystem" }}
    exchange.base-directory={{ .Values.trino.server.exchangeManager.baseDir }}
  {{- end }}  
  {{- range $configValue := .Values.trino.additionalExchangeManagerProperties }}
    {{ $configValue }}
  {{- end }}

  log.properties: |
    io.trino={{ .Values.trino.server.log.trino.level }}
  {{- range $configValue := .Values.trino.additionalLogProperties }}
    {{ $configValue }}
  {{- end }}

{{ if .Values.trino.eventListenerProperties }}
  event-listener.properties: |
  {{- range $configValue := .Values.trino.eventListenerProperties }}
    {{ $configValue }}
  {{- end }}
{{ end }}

{{- range $fileName, $fileContent := .Values.trino.worker.additionalConfigFiles }}
  {{ $fileName }}: |
    {{- $fileContent | nindent 4 }}
{{- end }}

{{- end }}
