{{- if .Values.trino.server.kerberosConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "peaka.trino.kerberos" . }}
  labels:
    app: {{ template "peaka.trino.fullname" . }}
    chart: {{ template "peaka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: kerberos
data:
  {{- toYaml .Values.trino.server.kerberosConfig | nindent 2 }}
{{- end }}
