{{- if .Values.trino.server.kerberosKeytab }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.trino.keytab" . }}
  labels:
    {{- include "peaka.trino.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.trino.server.kerberosKeytab | nindent 2 }}
{{- end }}
