apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "peaka.fullname" . }}-api-routes
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-api
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ include "peaka.ingress.entryPoint" . }}
  routes:
    - match: PathPrefix(`/{{ include "peaka.routes.apiPath" . }}`)
      kind: Rule
      priority: 10
      services:
        - name: {{ include "peaka.fullname" . }}-be-dispatcher
          port: http
          passHostHeader: true
  {{- if .Values.tls.enabled }}
  tls:
    secretName: {{ include "peaka.fullname" . }}-tls-secret
  {{- end }}

