apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "peaka.fullname" . }}-be-data-rest-routes
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-data-rest
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ include "peaka.ingress.entryPoint" . }}
  routes:
    - match: PathPrefix(`/{{ include "peaka.routes.servicePath" . }}/studioapi/data`)
      kind: Rule
      priority: 10
      middlewares:
        - name: {{ include "peaka.fullname" . }}-be-data-rest-auth-middleware
        - name: {{ include "peaka.fullname" . }}-be-data-rest-replace-path-middleware
      services:
        - name: {{ include "peaka.fullname" . }}-be-data-rest
          port: http
          passHostHeader: true
  {{- if .Values.tls.enabled }}
  tls:
    secretName: {{ include "peaka.fullname" . }}-tls-secret
  {{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "peaka.fullname" . }}-be-data-rest-auth-middleware
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-data-rest
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://{{ include "peaka.fullname" . }}-be-permission-service.{{ .Release.Namespace }}.svc.cluster.local:80/auth/data-rest-auth-check
    authResponseHeadersRegex: ^X-Internal-Authorization-
    authResponseHeaders:
      - "X-Peaka-User-Id"
      - "X-Peaka-Api-Key"
      - "X-Peaka-Username"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "peaka.fullname" . }}-be-data-rest-replace-path-middleware
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-data-rest
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  replacePathRegex:
    regex: "^/{{ include "peaka.routes.servicePath" . }}/studioapi/(.*)"
    replacement: "/${1}"