apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peaka.fullname" . }}-be-release-state
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-release-state
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.releaseState.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-release-state
      {{- include "peaka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-release-state
        {{- include "peaka.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        {{- if .Values.peakaContainerRegistryAccessSecret }}
        - name: {{ .Values.peakaContainerRegistryAccessSecret.name }}
        {{- end }}
        {{- range $_, $secret := .Values.imagePullSecrets }}
        - name: {{ $secret }}
        {{- end }}
      {{- if .Values.releaseState.serviceAccount.create }}
      serviceAccountName: {{ .Chart.Name }}-be-release-state
      {{- end }}
      containers:
        - name: release-state
          image: {{ default (include "peaka.image.registry" .) .Values.releaseState.image.registry }}/{{ .Values.releaseState.image.name }}:{{ .Values.releaseState.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.releaseState.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "peaka.fullname" . }}-env-config
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: CHART_NAME
              value: {{ .Chart.Name }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
          {{- with .Values.releaseState.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.releaseState.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.releaseState.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.releaseState.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.releaseState.terminationGracePeriodSeconds }}
      {{- end }}
      {{- include "peaka.common.nodeSelector" ( dict "nodeSelector" .Values.releaseState.nodeSelector "global" $.Values.global) | nindent 6 }}
      {{- with .Values.releaseState.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "peaka.common.tolerations" ( dict "tolerations" .Values.releaseState.tolerations "global" $.Values.global) | nindent 6 }}
