apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "peaka.hive.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "peaka.hive.name" . }}
data:
  metastore-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
          <name>metastore.thrift.uris</name>
          <value>thrift://{{ include "peaka.fullname" . }}-hive-metastore:{{ .Values.hiveMetastore.servicePort }}</value>
          <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>
      </property>
      <property>
          <name>metastore.task.threads.always</name>
          <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask,org.apache.hadoop.hive.metastore.MaterializationsCacheCleanerTask</value>
      </property>
      <property>
          <name>metastore.expression.proxy</name>
          <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          {{- if eq .Values.hiveMetastore.metastoreType "mysql" }}
          <value>com.mysql.cj.jdbc.Driver</value>
          {{- else if eq .Values.hiveMetastore.metastoreType "postgres" }}
          <value>org.postgresql.Driver</value>
          {{- else }}
          {{- fail "You can set either 'mysql' or 'postgres' in .Values.hiveMetastore.metastoreType." -}}
          {{- end }}
      </property>
      <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>{{ printf "jdbc:%s://%s:%s/%s" (include "peaka.metastore.connection" . ) (include "peaka.metastore.host" .) (include "peaka.metastore.port" .) (include "peaka.metastore.dbName" .) }}</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>{{ include "peaka.metastore.user" . }}</value>
      </property>
      <property>
          <name>javax.jdo.option.ConnectionPassword</name>
          <value>{{ include "peaka.metastore.password" . }}</value>
      </property>
      <property>
          <name>fs.s3a.access.key</name>
          <value>{{ include "peaka.objectStore.accessKey" . }}</value>
      </property>
      <property>
          <name>fs.s3a.secret.key</name>
          <value>{{ include "peaka.objectStore.secretKey" . }}</value>
      </property>
      <property>
          <name>fs.s3a.endpoint</name>
          <value>{{ include "peaka.objectStore.endpoint" . }}</value>
      </property>
      <property>
          <name>fs.s3a.path.style.access</name>
          <value>true</value>
      </property>
    </configuration>
