apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peaka.fullname" . }}-be-sql-service
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-sql-service
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sqlService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-sql-service
      {{- include "peaka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-sql-service
        {{- include "peaka.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        {{- if .Values.peakaContainerRegistryAccessSecret }}
        - name: {{ .Values.peakaContainerRegistryAccessSecret.name }}
        {{- end }}
        {{- range $_, $secret := .Values.imagePullSecrets }}
        - name: {{ $secret }}
        {{- end }}
      containers:
        - name: sql-service
          image: {{ default (include "peaka.image.registry" .) .Values.sqlService.image.registry }}/{{ .Values.sqlService.image.name }}:{{ .Values.sqlService.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.sqlService.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "peaka.fullname" . }}-env-config
          {{- with .Values.sqlService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.sqlService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.sqlService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.sqlService.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.sqlService.terminationGracePeriodSeconds }}
      {{- end }}
      {{- include "peaka.common.nodeSelector" ( dict "nodeSelector" .Values.sqlService.nodeSelector "global" $.Values.global) | nindent 6 }}
      {{- with .Values.sqlService.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "peaka.common.tolerations" ( dict "tolerations" .Values.sqlService.tolerations "global" $.Values.global) | nindent 6 }}
